.home {
  display: flex;
  color: #1FB860;
  font-size: 14px;
}
.page-container{
  background: #fff;
  height: 100%;
  overflow: hidden;
  .header-title{
    margin-top: 20px;
    h2{
      font-size: 20px;
    }
    p{
      font-size: 16px;
    };
  }
  .page-content-middle{
    padding: 10px 0;
    .content-img{
      img{
        width: 100%;
        height: 100%;
        border: 1px solid black;
        border-radius: 10px;
      }
    }
  }
}