.home {
  display: flex;
  color: #1FB860;
  font-size: 14px;
}

.page-container {
  background: #fff;
  height: auto;
  overflow: hidden;

  .header-title {
    margin-top: 20px;

    h2 {
      font-size: 20px;
    }

    p {
      font-size: 16px;
    }
  ;
  }

  .page-content-middle {
    padding: 10px 0;

    .content-img {
      img {
        width: 100%;
        height: 100%;
        //box-shadow: -1px 1px 11px rgb(58 58 58);
        border-color: rgba(0, 0, 0, .05);
        -webkit-box-shadow: 0 4px 5px 0 rgba(0, 0, 0, 0.14), 0 1px 10px 0 rgba(0, 0, 0, 0.12), 0 2px 4px -1px rgba(0, 0, 0, 0.2);
        box-shadow: 0 4px 5px 0 rgba(0, 0, 0, 0.14), 0 1px 10px 0 rgba(0, 0, 0, 0.12), 0 2px 4px -1px rgba(0, 0, 0, 0.2);
        border-radius: 10px;
      }
    }
  }

  .page-content-list {
    border-color: rgba(0, 0, 0, 0.14);
    -webkit-box-shadow: 0 4px 5px 0 rgba(0, 0, 0, 0.14), 0 1px 10px 0 rgba(0, 0, 0, 0.12), 0 2px 4px -1px rgba(0, 0, 0, 0.2);
    box-shadow: 0 4px 5px 0 rgba(0, 0, 0, 0.14), 0 1px 10px 0 rgba(0, 0, 0, 0.12), 0 2px 4px -1px rgba(0, 0, 0, 0.2);
  }
}